(in-package :function-cache-test)

(defclass metered-cache (hash-table-function-cache metered-mixin)
  ())

(defcached (test-metered :cache-class 'metered-cache) (a)
  a)

(define-test metered-test ()
  (function-cache:reset-counters 'test-metered)
  (clear-cache 'test-metered)
  (assert-eq 0 (hits *TEST-METERED-CACHE*))
  (assert-eq 0 (misses *TEST-METERED-CACHE*))
  (test-metered 0)
  (assert-eq 0 (hits *TEST-METERED-CACHE*))
  (assert-eq 1 (misses *TEST-METERED-CACHE*))
  (assert-eq 0 (hit-ratio *TEST-METERED-CACHE*))
  (test-metered 0)
  (assert-eq 1 (hits *TEST-METERED-CACHE*))
  (assert-eq 1 (misses *TEST-METERED-CACHE*))
  (assert-eql 1/2 (hit-ratio *TEST-METERED-CACHE*))
  )

(define-test clearing-resets-meters ()
  (function-cache:reset-counters 'test-metered)
  (assert-eq 0 (hits *TEST-METERED-CACHE*))
  (assert-eq 0 (misses *TEST-METERED-CACHE*))
  (test-metered 1)
  (function-cache:reset-counters 'test-metered)
  (assert-eq 0 (hits *TEST-METERED-CACHE*))
  (assert-eq 0 (misses *TEST-METERED-CACHE*)))
